FROM nginx:1.25.3

COPY . /usr/share/nginx/html

RUN find . -type f -name "*.js" -exec sed -i 's|http://localhost:8080\(/[^"]*\)|https://www.autosup.fun/api\1|g; s|http://localhost:8081\(/[^"]*\)|https://www.autosup.fun/api\1|g' {} +


EXPOSE 80
