services:
  db:
    build:
      context: ./sql/config/
      dockerfile: Dockerfile.prod
    volumes:
      - ./sql/prod:/var/lib/mysql
    env_file:
      - sql-password.env.prod

  client:
    build:
      context: ./client
      dockerfile: Dockerfile.prod

  server:
    build:
      context: ./server
      dockerfile: Dockerfile.prod
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE="prod"
      - DB_HOST="db"
      - DB_PORT="3306"
      - DB_USER_NAME="root"
      - DB_USER_PASSWORLD="supersecurepassword"
    # networks:
    #   - proxy-network

    depends_on:
      - db
# networks:
#   proxy-network:
#     external: true
