FROM openjdk:17.0.2-slim-buster as builder
WORKDIR /build
COPY . /build
RUN ./gradlew build -x test

FROM openjdk:17.0.2-slim-buster
WORKDIR /app
COPY --from=builder /build/build/libs/*.jar /app/app.jar
EXPOSE 8080
CMD ["java", "-jar", "app.jar"]
